-- This will run last in the setup process and is a good place to configure
-- augroups/autocommands and custom filetypes. This just runs pure lua so
-- anything that doesn't fit in the normal config locations above can go here.

-- Example: Set up custom filetypes
-- vim.filetype.add {
--   extension = {
--     foo = "fooscript",
--   },
--   filename = {
--     ["Foofile"] = "fooscript",
--   },
--   pattern = {
--     ["~/%.config/foo/.*"] = "fooscript",
--   },
-- }
